### ISSUE TITLE
ClientTracer.setCurrentClientServiceName should not be used by ClientRequestInterceptor

### ISSUE THREAD

**Issue by chemicL** [openzipkin/brave#153]
Brave should use the default endpoint when reporting client side spans (the same way server behaves)
Currently `ClientRequestAdapter.getClientServiceName` method is used to extract the endpoint service name, however the documentation is misleading by saying:

> The service name is expected to be the same as the service we are calling.

**Comment by adriancole** [comment]
I agree this is a mistake,  especially  if you read the Javadoc on the
method eventually  invoked (which says the endpoint is the local one)

Two options (which can be done one after other or just first)
* assume there is a valid feature for dynamically  changing  service name,
but fix the doc to say it is the local service.
* remove  the client service name method,  fields,  and associated
provider.

The latter makes more sense to me as it feels strange  to only allow
dynamic  names on the client but not the server. Usually  people tell me
the server's name is authoritative vs the client. The recommendation  would
be to just make a new Brave when you want to change the service name.  This
could be aided by a Brave builder like..  scoped = new
Brave.Builder(parent).serviceName("alternate").build();

I tried this locally and it reduces a lot of code complexity  only added to
support client service name changes. It will also increase our test
coverage :) Downside  is that it is a picture breaking.

**Comment by kristofa** [comment]
The reason why we started implementing this behaviour in Brave, using server side service name for the client side endpoint, is explained here: https://groups.google.com/forum/#!topic/zipkin-user/Q_EZp3pQXk4.

**Comment by adriancole** [comment]
Heh. Thanks for unveiling  the source of confusion. That mail thread
basically says if you ask a few people they might have a few answers.

Several months back, we documented  the constants and what they are used
for. Also, validating with Twitter.

The address annotations were added to resolve the ability to name the
destination and tag the IP.

Moreover, the local service name is what finagle logs on 'cr' etc unless
you hack up things to override it. This means that most finagle users will
be logging the local service name on 'cr' particularly  due to how
difficult and awkward it is to override it.

If we think that the client should name the destination is the right choice
(again) then maybe we should reopen the discussion that led to the
constants in thrift being documented as local. If so, we ought to give a
good reason for why, and in consideration that server_address exists.

For example,  that mail thread only had Brian say 'this is wrong.' he
offered no rationale or other explanation. It is even possible  he was
mistaken as these  things are very subtle. Personally, I think the later
work we did where we literally  raised a public request to document the
intent of the annotations, verifying things like this with Twitter, holds
more weight than someone jumping in to say 'nope'

The most recently understood thing (which was that all annotations are log
statements and they log the service name of the tracer) is far simpler than
the alternative: which would read like 'annotation is a log statement
except when it is a 'cs' because then the endpoint has the name of the
destination but the ip address of the source.' Such an explanation would
also be inconsistent with 'sr' which doesn't try to log the service name of
the caller. It would also make server_address even stranger, and doesn't
match with Opentracing which is using 'peer.service' for the function of
naming the remote side.

Moreover, we need to ack that in many cases people are overriding anything
the client supplies. For example, there was recently a change in zipkin to
allow service name to be empty as the client's service name is often wrong.

All of this said,  there could be some reason to special case client
service name even though we have server_address. If we can materialize such
a reason, I would support having the asymmetric feature where client
service name is overrideable, more so than the server side. However, that
should be a good enough reason to tell other tracers to do the same. IMHO,
that has to be a better reason than Brian said so.

**Comment by kristofa** [comment]
The main reason why we did this change in the past was because it improved visualisation of traces in zipkin-web.  

I wonder what happens today for displaying `service name` in zipkin-web when we have 2 different values (one for client, one for server) for a 1 span.  I guess it select one and is consistent in which it picks.

I agree that we don't need to stick to this old behaviour and agree it is confusing. We can always fix the visualisation if that would still be a problem.

**Comment by adriancole** [comment]
> The main reason why we did this change in the past was because it improved
> visualisation of traces in zipkin-web.
>
> I wonder what happens today for displaying service name in zipkin-web
> when we have 2 different values (one for client, one for server) for a 1
> span. I guess it select one and is consistent in which it picks.
>
the relevant logic is here, which was recently converted from scala to
javascript. it is an if-statement chain :)

https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/component_ui/traceSummary.js#L45


> I agree that we don't need to stick to this old behaviour and agree it is
> confusing. We can always fix the visualisation if that would still be a
> problem.
>
yeah as much as I don't like the UI code involved, it is already trying to
handle this problem and we can try to improve it as necessary

**Comment by eirslett** [comment]
> We can always fix the visualisation if that would still be a
 problem.

+1. I'd rather have the complexity in the UI code than have it in the reporters.

**Comment by adriancole** [comment]
ok here's a bold pull request https://github.com/openzipkin/brave/pull/156

**Comment by eirslett** [comment]
Ouch... I finally (too late :cry: ) realised this is a problem for FINN's usage of Brave... we rely heavily on setting the service name on the client side (we do it on every request actually).
The main use case is to annotate remote services that are not themselves instrumented by Brave or any other Zipkin reporter. This could for example be MySQL, PostgreSQL, Cassandra etc., or also one of our own internal microservices that happens to not be instrumented yet - maybe the deveopers haven't bothered to instrument the application, it's written in a language without a Zipkin implementation (haskell?)
Unfortunately, we upgrade Brave with this change, without some other way of setting the remove service name...

I agree that the method name was confusing. Maybe it should be`Brave.setCurrentRemoteServiceName("mysql")`?

**Comment by adriancole** [comment]
commented elsewhere, but the correct way to address the use case
you're mentioning is in the overload of `tracer.setClientSent()`. Ex.
you'll see some code using that to specify the peer's service, ip etc.
