### ISSUE TITLE
Parent Id not getting generated for brave-jersey and tree structure is not displayed in UI

### ISSUE THREAD

**Issue by anujkumarnag** [openzipkin/brave#190]
Hi,

Please find attached sample application and modified brave-jersey filter with hard code brave initialization.

Also I am attaching the web ui screen shot as well.

The issue is the traces are getting logged individually from client services but the call graph tree is not getting created.

Sample Jersey(1) application have 2 api:
1) GET: rest/hello/{param}
    this API internally calls second API

2) GET rest/hello/{param}/time

The trace of first and second API call is coming separately a when I call the first API from client.
the client trace is having the traces for client side and first API both but the second API trace is not coming.

[Uploading Web-UI-ScreenShots.docx…]()
[Uploading brave-jersey.zip…]()
[Uploading jersey-app.zip…]()

Thanks for all your help!!

**Comment by anujkumarnag** [comment]
Re-uploading the files:
[brave-jersey.zip](https://github.com/openzipkin/brave/files/324784/brave-jersey.zip)
[jersey-app.zip](https://github.com/openzipkin/brave/files/324785/jersey-app.zip)
[Web-UI-ScreenShots.docx](https://github.com/openzipkin/brave/files/324786/Web-UI-ScreenShots.docx)

**Comment by adriancole** [comment]
This type of issue is not likely to succeed as it implies someone will
download and find something to view word docs, install and run the
applications and then try to figure out what the problem is.

Double-check the README from brave first. For example, it has instructions
to register a filter before making a client call

https://github.com/openzipkin/brave/tree/master/brave-jersey2

Also, you can consider using something like dropwizard or spring to
configure your application such that a configured client can be injected as
opposed to instantiated directly.

https://github.com/smoketurner/dropwizard-zipkin

**Comment by adriancole** [comment]
Brave 4.3 includes new support for jaxrs2: brave-instrumentation-jaxrs2 try again?
