### ISSUE TITLE
how to use brave in my application

### ISSUE THREAD

**Issue by galen-guo** [openzipkin/brave#257]
how to integrate brave with my Application? Is there any introduction about this?

**Comment by dragontree101** [comment]
https://github.com/openzipkin/brave-resteasy-example

**Comment by galen-guo** [comment]
my application front-end is servlet, and many components in the middle, and the back-end is DB, how can I integrate the Brave with my application?

**Comment by galen-guo** [comment]
https://github.com/openzipkin/brave-resteasy-example seems not my needed

**Comment by dragontree101** [comment]
i think brave is zipkin's api, you will call brave's api to produce zipkin's span in you application and send these span to zipkin's store(cassandra or es) by collector(kafka or scribe).

**Comment by jpiechowka** [comment]
@galen-guo You can try [Wingtips](https://github.com/Nike-Inc/wingtips) In my opinion it is better documented and easier to use.

**Comment by adriancole** [comment]
>
> @galen-guo <https://github.com/galen-guo> You can try Wingtips
> <https://github.com/Nike-Inc/wingtips> In my opinion it is better
> documented and easier to use.
>
:) classy...

**Comment by adriancole** [comment]
Brave is a collection of components used to instrument libraries. For
example, if you look at the naming convention of components, they
correspond to libraries.

Ex "brave-jersey2" is brave integration for the jersey 2 (rest) library and
"brave-p6spy" is integration for JDBC connection pools.

If you are using brave directly, you would configure your applications to
use these components, possibly making new ones where they don't exist. You
could alternatively use products that layer on top (such as
dropwizard-zipkin).

If you are looking for something that automatically does everything, with
no code or configuration in application artifacts, and you aren't using
something like spring boot or dropwizard...

Then you are probably seeking something like a JVM agent. We currently
don't have a list of JVM agents that use Brave or otherwise, but there are
APM systems that have zipkin integration or similar functionality. If you
want to ask more about that, it is better to use gitter or the zipkin-user
google group since it is certainly out of scope here.

https://gitter.im/openzipkin/zipkin
https://groups.google.com/forum/#!forum/zipkin-user
