### ISSUE TITLE
Allow disabling tracing for certain resources with brave-jaxrs2

### ISSUE THREAD

**Issue by robinst** [openzipkin/brave#303]
Hi! We started using this library and it's really nice so far. We're using `brave-jaxrs2` to configure tracing on Jersey resources.

We have some resources where we want to disable tracing (a healthcheck endpoint that gets called frequently by Amazon's ELB). To do that, I've written a `DynamicBraveTracingFeature` that works like this:

```java
public class DynamicBraveTracingFeature implements DynamicFeature {

    private final Brave brave;
    private final SpanNameProvider spanNameProvider;

    public DynamicBraveTracingFeature(Brave brave, SpanNameProvider spanNameProvider) {
        this.brave = brave;
        this.spanNameProvider = spanNameProvider;
    }

    @Override
    public void configure(ResourceInfo resourceInfo, FeatureContext context) {
        if (resourceInfo.getResourceClass().isAnnotationPresent(DisableTracing.class) ||
                resourceInfo.getResourceMethod().isAnnotationPresent(DisableTracing.class)) {
            return;
        }
        context.register(BraveContainerRequestFilter.builder(brave).spanNameProvider(spanNameProvider).build());
        context.register(BraveContainerResponseFilter.create(brave));
    }
}
```

There's also an annotation called `DisableTracing` (omitted for brevity). What that allows is to disable tracing for a specific resource on the class or method level like this:

```java
@Path("/healthcheck")
@DisableTracing
public class HealthcheckResource {
    // ...
}
```

I'm wondering if that is something that you'd like to see us upstream. If yes, I can add a builder and documentation and submit a PR. What do you think?

**Comment by adriancole** [comment]
definitely sensible to filter out resources. Unless you are expecting other dynamic features, I might name this feature FilteringBraveFeature or similar

Before you invest too much in a specific annotation. I'd look at how others are doing pattern exclusion for http tracing. If you need breadcrumbs let me know.

**Comment by robinst** [comment]
> Before you invest too much in a specific annotation.

Not sure what you mean, it would be a new annotation living in the `brave-jaxrs2` artifact.

> I'd look at how others are doing pattern exclusion for http tracing. If you need breadcrumbs let me know.

Others? In Jersey? Breadcrumbs please?

**Comment by adriancole** [comment]
> Before you invest too much in a specific annotation.
>
> Not sure what you mean, it would be a new annotation living in the brave-jaxrs2 artifact.

Sorry, what I meant to say is that something like this would bind
business code directly to the tracing library. It would cause a
coupling concern especially when brave updates.

I think this approach is used, you'll notice it noted as one of two
ways to skin cat here, though incidentally the latter below is a bit
more dynamic (predicate based)

http://stackoverflow.com/questions/23641345/jersey-request-filter-only-on-certain-uri

A way to decouple from a specific type (make it more dynamic) would be
to have a predicate on ResourceInfo. This wouldn't prevent pinning to
an annotation (regardless of if that annotation is in brave or not).
And it can also handle a common case which is don't trace static
assets. Ex braveFeatureBuilder.exclude(hasAnnotation(MyTracingDisabled.class))
or.. braveFeatureBuilder.excludePattern("favicon.ico")

Another way is to use composition.. For example, if you disable
tracing prior to the normal trace filter, you'd get what you want as
well.

It is actually really simple! set the header "X-B3-Sampled: 0" in some
prior filter. this doesn't even need brave classes to work.

> I'd look at how others are doing pattern exclusion for http tracing. If you need breadcrumbs let me know.
>
> Others? In Jersey? Breadcrumbs please?

Sure. here are some examples.
https://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_http_filter
< pattern-based path filter (note that since sleuth supports non-http
it has an http prefix. we don't need this for jaxrs-2)
https://github.com/openzipkin/zipkin-ruby/blob/22dfe546657aaf04d8bfc53ce3dd37f574d925ac/README.md#filter_plugin

**Comment by robinst** [comment]
Thanks for the pointers!

> A way to decouple from a specific type (make it more dynamic) would be to have a predicate on ResourceInfo.

That sounds good. So the API for this would be that users pass a `java.util.function.Predicate<ResourceInfo>` when building the `FilteringBraveFeature`. If it matches, apply the brave filters. Or we could reverse it and make it an exclusion filter. If that sounds good to you then I'll put that in a PR.

> Ex braveFeatureBuilder.exclude(hasAnnotation(MyTracingDisabled.class)) or.. braveFeatureBuilder.excludePattern("favicon.ico") 

These sound like convenience methods. How would they interact with the `Predicate` based approach? We could build a list of predicates and disable tracing when one of them matches.

> Another way is to use composition.. For example, if you disable tracing prior to the normal trace filter, you'd get what you want as well.
>
> It is actually really simple! set the header "X-B3-Sampled: 0" in some prior filter. this doesn't even need brave classes to work.

I considered this but it seemed more like a workaround than a nice solution. It adds a header that wasn't there in the original request. This would make logging and possibly other things confusing.

**Comment by adriancole** [comment]
so I wasn't thinking literally j.u.f.Predicate as that's a java 8 type. I would also not encourage making composition too fancy, or in scope. rather accept a single predicate, add a pattern default and leave anything else up to the user.

```java
ex. a nested inner type or something..
public interface ExclusionFilter {
  boolean shouldExclude(ResourceInfo info);
}
```

then you have one helper method for excluding by path (since it is common and doesn't require anything special to achieve)

ex.
```java
Builder exclude(ExclusionFilter exclude) {
this.exclusionFilter = exclude; // null check etc
return this;
}

Builder excludePattern(String pattern) {
  realPattern = Pattern.compile... // so users aren't bothered by regex mechanics
  return exclude(info -> realPattern.blah); // note you can use lambda even in java 6 thx to retrolambda
}
```

**Comment by robinst** [comment]
Sounds good, I'll try to put a PR together tomorrow.

**Comment by robinst** [comment]
Looked into this now, but there's a problem. The `excludePattern` can not be implemented using a `DynamicFeature`, because all it gets is the `javax.ws.rs.container.ResourceInfo`, which only has `getResourceMethod` and `getResourceClass`, but no URI.

I'm wondering if the exclusion should be applied in `BraveContainerRequestFilter` instead, using the information available in `ContainerRequestContext`. The filter could be added as an additional builder method on `BraveTracingFeature` and then passed on to `BraveContainerRequestFilter`.

Not sure if that approach would still allow filtering based on annotations though, because `ContainerRequestContext` doesn't seem to include the resource info.. I'd be interested to know what you think.

**Comment by adriancole** [comment]
>
> I'm wondering if the exclusion should be applied in
> BraveContainerRequestFilter instead, using the information available in
> ContainerRequestContext. The filter could be added as an additional
> builder method on BraveTracingFeature and then passed on to
> BraveContainerRequestFilter.
>
yes I think this is the best place for this. it may need to just be a
special-cased feature vs a generic predicate

> Not sure if that approach would still allow filtering based on annotations
> though, because ContainerRequestContext doesn't seem to include the
> resource info.. I'd be interested to know what you think.
>
not sure if annotations isn't better as a dynamic feature or not.. we could
have the annotation-specific variant as a how-to.
another option is injecting the resource info using a Context anntation or
something.

**Comment by adriancole** [comment]
Brave 4.3 is being synced now, and supports path-based sampling.

**Comment by robinst** [comment]
Anyone wondering where the API for "path-based sampling" is, see class `brave.http.HttpSampler` in the `brave-instrumentation-http` artifact here, Javadoc here:

https://www.javadoc.io/doc/io.zipkin.brave/brave-instrumentation-http/4.3.3

**Comment by adriancole** [comment]
@robinst see #433 for a generic http sampler implementation. There's currently a way to roll your own noted here:

https://github.com/openzipkin/brave/tree/master/instrumentation/http#sampling-policy

**Comment by adriancole** [comment]
also see #437 for a built-in route based sampler (note this will still instrument things)
