### ISSUE TITLE
Feature Request - Binary tags

### ISSUE THREAD

**Issue by pcwinters** [openzipkin/brave#415]
As of v4.3, Brave only supports `String` tag values. The underlying Recorder machinery builds tags values as zipkin binary annotations. Please implement `public Span tag(String name, byte[] value);` on `brave.Span`.

**Comment by adriancole** [comment]
Zipkin itself discourages binary tags, so this decision was intentional.

Why are you looking to store binary data in zipkin?

**Comment by pcwinters** [comment]
I'm interested in leveraging Brave for e2e testing of a distributed, asynchronous message processing pipeline. I don't intend to store any binary data in zipkin. I plan to use spans for tracking completion stages and short-circuiting failures in long running asynchronous tests. There are cases where I'd like to push encoded data with tags. We'll avoid having to instrument our services twice, since this will fit in very comfortably with Brave. 

The inability to produce binary annotations doesn't block me, but it seems like a valuable feature to at least support, even if it's discouraged for most use cases.

**Comment by adriancole** [comment]
Thanks for the context. It would take a lot of people asking to reverse
this course as "binary annotations" have been the cause of a lot of
cognitive and technical burden historically.

the reason it is discouraged here is because the binary type will end up
being dropped. We don't want to lead people down a path which ends up as a
cliff, that would feel worse than saying so up front.

https://github.com/openzipkin/zipkin/issues/1499

I would suggest doing your own encoding, as we aren't likely to break that.
Brave 4's model aligns well at the moment with the forward path upstream.

**Comment by jorgheymans** [comment]
No binary tags it is.
