### ISSUE TITLE
Clock.currentTimeMicroseconds() broken in Brave 4.11

### ISSUE THREAD

**Issue by Logic-32** [openzipkin/brave#564]
According to https://github.com/openzipkin/brave/releases/tag/4.11.0 time should work better in Brave 4.11 but (on JRE7 at least), it actually doesn't.  Clock.currentTimeMicroseconds() actually returns milliseconds according to: https://github.com/openzipkin/brave/commit/c5e164a06ba4f909ad0ce4700e97ef16f5b5ed15#diff-7e8a5d8cee6bb38ae6998b05432624e1

This is a slight problem for me as I had to directly call that method for some Zipkin 1 based code I was working on.  Now, in  Zipkin 2, I may be able to get rid of it.  But the point is that it is still broken and not even documented as such.

Can we at least update it to add the current nanoTime() in for true (though debatably accurate but consistent with how it was) microseconds?  This would not affect Trace-level accuracy of time but simply make it so the function returns a reasonable value if it is needed elsewhere.

For reference, I'm also using Brave 4.13.1.

Edit: I suppose it would be reasonable to consider the real "bug" here being, how do I call Span.start(long) without an accurate microsecond measurement?  Typically, you'd get the Clock off the Tracing object and use that.  But now it's unreliable as anything you don't explicitly set a timestamp on will be accurate to the microsecond and everything else will be millisecond.

**Comment by adriancole** [comment]
the clock is the raw supplier of time. It is read once and then thereafter uses nanoseconds offset during the span, at least latest versions. I wouldn't use Span.start(long), rather use Span.start() as it has the behavior you are looking for anyway, right? https://github.com/openzipkin/brave/pull/547

**Comment by adriancole** [comment]
ps it could be possible to make us expose a trace-sensitive clock, which would use offsets and still detect time changes..

just before going down that path, can you elaborate why you are using start(long) as opposed to just start()

**Comment by Logic-32** [comment]
First, my two cents: if `start(long)` is available as part of the API there should be a reasonable way to make sure you're using the same "clock" that is being used internally.  Otherwise, and we have seen this a bit in our system, the traces show up rather weird in the UI.

But that aside, my specific use case is that I do kind of need it.  We rolled our own JDBC instrumentation because, at the time, Brave 4 didn't have an easy way to support it (not sure if it does yet either).  What we want is to be able to trace the life of a JDBC Connection but _only if_ a query is executed on it.  So we defer starting the span until the first execution.  But in order to accurately represent the life of the Connection we have to start the span in the past.  Does that make sense?

p.s. Yes, it is weird to create a Connection and not execute anything on it.  But not every dev knows to check if a collection isEmpty _before_ opening one.  So we're trying to be flexible with semi-legacy code :)

**Comment by adriancole** [comment]
Very valid points. This is all tradeoff, as bear in mind the old clock
skipped NTP updates causing havoc for others. That was the motivation for
the scoping change (from global ticks to trace-scoped ticks). Let's discuss
a bit.

First, my two cents: if start(long) is available as part of the API there
> should be a reasonable way to make sure you're using the same "clock" that
> is being used internally. Otherwise, and we have seen this a bit in our
> system, the traces show up rather weird in the UI.
>
First thing maybe we should do is deprecate that api. It was only added for
opentracing and there are other ways to accomplish that. In hindsight it
was a mistake for reasons including inheriting our responsibility to
platform-level clock providers!

Now, keep in mind that you are in control of the clock used. You can
provide a NTP skipping clock like we used to have, and that will be sent
back to you when you call tracing.clock(). That's one option.

> But that aside, my specific use case is that I do kind of need it. We
> rolled our own JDBC instrumentation because, at the time, Brave 4 didn't
> have an easy way to support it (not sure if it does yet either). What we
> want is to be able to trace the life of a JDBC Connection but *only if* a
> query is executed on it. So we defer starting the span until the first
> execution. But in order to accurately represent the life of the Connection
> we have to start the span in the past. Does that make sense?
>
We have a new api I think you should consider, which is span.abandon().
This was made for this purpose. You can start the span and if you decide it
wasn't useful, call abandon. Would that help?


> p.s. Yes, it is weird to create a Connection and not execute anything on
> it. But not every dev knows to check if a collection isEmpty *before*
> opening one. So we're trying to be flexible with semi-legacy code :)
>
This seems a nice feature to consider for our database instrumentation..
Maybe you can open an issue so that we address this in mysql, p6spy and
whatever happens next?

Finally, I'm offering workarounds just because the problem is strange.. One
nice thing we can do is if you ask for the clock we can give you one for
the "current span" If all your database connections happen in the context
of an existing trace, this could work. That said, I'd prefer to see if you
can avoid using clock in the mean time.. let me know if any of the above
info changes anything.

**Comment by jorgheymans** [comment]
> want is to be able to trace the life of a JDBC Connection but *only if* a
 query is executed on it. So we defer starting the span until the first

but given that https://github.com/openzipkin/brave/blob/c27a668fa833d511c48f2c74d29b6552614e3407/instrumentation/p6spy/src/main/java/brave/p6spy/TracingJdbcEventListener.java#L34 runs only when there is an actual statement being executed, would this not be sufficient for your case ? No spans will be created unless something is executed IIUC.

**Comment by Logic-32** [comment]
Love the discussion!  You guys move pretty fast on this stuff so I appreciate having a few things pointed out that I missed.

For the sake of discussion...

> First thing maybe we should do is deprecate that api. It was only added for
opentracing and there are other ways to accomplish that. In hindsight it
was a mistake for reasons including inheriting our responsibility to
platform-level clock providers!
> ...
> One nice thing we can do is if you ask for the clock we can give you one for
the "current span"

Given the change to how the clocks work I'm in favor of the deprecation.  Mostly because, at the moment, there is no way to keep things consistent.  In the event that API is somehow useful to others and not removable, instead of my providing an NTP skipping Clock to Tracing or referring to the "current span" (which, I suppose, may not always be set), can we add a `getClock()` method to Span directly perhaps?  That way we can use it's internal clock to keep timing information consistent and there is no "magic behind the scenes" happening.

> We have a new api I think you should consider, which is span.abandon().
This was made for this purpose. You can start the span and if you decide it
wasn't useful, call abandon. Would that help?

Very much so!  I will see how it integrates to our framework but that would, on the surface, fit the use case exactly :)

@jorgheymans, I wasn't around when we did our database instrumentation but for whatever reason P6spy wasn't used.  Now it would be somewhat expensive to change.  However, yes, that would seem to fit our use case also!  But there are other differences in P6 that may not be acceptable from what I'm looking at.  Which is ironic because our implementation looks _very_ similar to it.  They are also difference which I wouldn't be inclined to change in P6 necessarily (such as deciding how spans are named).

@adriancole, given all of this, I'll let you decide if this needs to remain open for any API changes/etc.  But I at least have some workarounds to experiment with.  So thank you!

**Comment by adriancole** [comment]
I think the best first step is to change the impl of the clock to use the
current span.
 * If you don't have a current span when you should, then that's a bug
anyway :)
 * If you don't have a current span because a trace hasn't started, the
problem is limited to millis resolution on your JVM
 * Otherwise, you'll be fine I think

Reason I like this is that the workaround is not api affecting and I think
it will improve your situation enough to not be noticable. We can do
deprecation etc as a separate step.

SG?

**Comment by Logic-32** [comment]
> If you don't have a current span because a trace hasn't started, the
problem is limited to millis resolution on your JVM
I suppose the documentation on Clock itself implies that `millis * 1000` is a legitimate return response.  My big fuss is that the method is called `currentTimeMicroseconds()` and isn't, itself, documented that that the method name is a bit of a lie (e.g. can return millis).

As for the workaround, it would not improve my situation because I'm working in that "trace hasn't started yet" situation.  I'm trying to setup the span at the time I check the Clock and then use it to call `start()`.

Thankfully, I've been able to refactor everything in such a way that I no longer need the Clock (thanks again for the `abandon()` tip).  If the start/finish/annotate/etc... methods that took a timestamp were to be deprecated that would make me happy.  But the irony is that they'll work fine in Java 9 by the looks of it so it might not be the right course of action?  Either way, it's quite bothersome that Java makes working in microseconds so hard.

Actually, as I write this, the clocks still won't be consistent in Java 9 right?  Because a new TickClock will be returned that has a different implementation than Clock itself.  So there is no way to get consistent times.  If I call `start()` (no time argument) and then `annotate(long, String)`, that annotation will probably show up somewhere very random right?

**Comment by adriancole** [comment]
>
> As for the workaround, it would not improve my situation because I'm
> working in that "trace hasn't started yet" situation. I'm trying to setup
> the span at the time I check the Clock and then use it to call start().
>
This should only be a problem if you have no trace, meaning you've called
nothing upstream to that database call. For example, if the trace starts
with an incoming http request or message, or some scheduled task that's
already started, then the clock approach I mentioned would work because it
is "trace scoped" not span scoped. Does this make sense? Are most of your
SQL calls root spans? or are they a part of an existing trace. If part of
an existing trace, are they children of another span in the same process?
If so, the clock should be coherent with this approach.

> Thankfully, I've been able to refactor everything in such a way that I no
> longer need the Clock (thanks again for the abandon() tip). If the
> start/finish/annotate/etc... methods that took a timestamp were to be
> deprecated that would make me happy. But the irony is that they'll work
> fine in Java 9 by the looks of it so it might not be the right course of
> action? Either way, it's quite bothersome that Java makes working in
> microseconds so hard.
>
Java 9 removes the problem about the resolution of the initial timestamp in
a trace, by changing it from millis to micros (incidentally this is using
the same api as java 8, just that the impl is micros resolution)

> Actually, as I write this, the clocks still won't be consistent in Java 9
> right? Because a new TickClock will be returned that has a different
> implementation than Clock itself. So there is no way to get consistent
> times. If I call start() (no time argument) and then annotate(long,
> String), that annotation will probably show up somewhere very random
> right?
>
A trace-scoped clock would allow manual use of the "long timestamp"
signatures, but in most cases I think we still should encourage people to
use the implicit time rather than doing so manually. We receive very few
inquiries on this functionality as it is very much edge case.

To further elaborate what I mean..

we expose a clock that looks at any current span. To add an annotation
requires that you've already started a span, so the clock would be
congruent with that. To start a child span in an existing trace, the
*first* span in that trace local to the host establishes the clock tick.
This means any future spans (usually SQL calls are leaves not root spans)
will have the correct timestamp.

**Comment by Logic-32** [comment]
> This should only be a problem if you have no trace, meaning you've called
nothing upstream to that database call. For example, if the trace starts
with an incoming http request or message, or some scheduled task that's
already started, then the clock approach I mentioned would work because it
is "trace scoped" not span scoped. Does this make sense? Are most of your
SQL calls root spans?

I did some searching and found at least one use case where we were not doing this strictly with JDBC spans.  We wanted a non-SR/SS annotation added at the exact start of a span so we could identify some latency in a particular process.  So we set both with the same timestamp.  That aside, I was talking to one team awhile back and they want to exclusively trace JDBC calls.  It's a bit absurd but it's what they wanted.  Meaning there'd be no root in that case either.

> To add an annotation requires that you've already started a span

We actually start spans last and name/annotate as much as we can prior to doing so.  I swear I read somewhere that doing so helps avoid a certain amount of locking but I have no idea where that reference was.  Either way, while I can agree that looking to the current span would help alleviate a certain amount of issues it makes for a confusing API imo because `currentTimeMicroseconds()` would then have two different behaviors depending on some magical context.  Of which, that context is actually optional if I read the code right.  For it to work, you would have to voluntarily call `withSpanInScope()`, correct?  Without doing so, you'll never have a "current span."

**Comment by adriancole** [comment]
Thanks for the notes, looks like you are indeed using the apis. Goal here
for us is to not reintroduce known problems when handling edge cases..
maybe we should go a different route.

What if you had a function to get a clock given a trace context? (explicit
vs magic context) This still places it squarely in "edge case" category,
but could get you consistent time. Regardless, of magic constant or not,
there is no race condition.. the clock I mentioned would get you a tick
that would then be constant for the trace without regards to whether
span.start was called first or something else..

PS on performance things, adding tags is pretty typical pre-start, for
reasons you mentioned. Adding timestamp annotations is a bit odd eventhough
it does't break anything at the moment (except some people's assumptions).

**Comment by Logic-32** [comment]
I suppose that wouldn't be unreasonable.  The time relative to a trace seems contextual enough that a TraceContext can hold one.  And Spans have TraceContexts already anyway.  So it should solve my concern and not reintroduce any issues I don't think.  As long as you're ok with it I approve :)

Thanks for the brainstorming!

**Comment by adriancole** [comment]
Heheh i dont usually suggest things that will hurt later.. at least not
intentionally! Will try and see if it is not painful next week

On 13 Jan 2018 7:51 am, "Logic-32" <notifications@github.com> wrote:

I suppose that wouldn't be unreasonable. The time relative to a trace seems
contextual enough that a TraceContext can hold one. And Spans have
TraceContexts already anyway. So it should solve my concern and not
reintroduce any issues I don't think. As long as you're ok with it I
approve :)

Thanks for the brainstorming!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/openzipkin/brave/issues/564#issuecomment-357386357>,
or mute
the thread

**Comment by adriancole** [comment]
oops totally meant this to be a PR review! please give feedback post-merge if you can https://github.com/openzipkin/brave/commit/84e78636fe16521c01749dd39ab7c0e367583d61

**Comment by Logic-32** [comment]
Done.  Need me to try and re-open this or anything else?

**Comment by adriancole** [comment]
I am still interested in understanding your use case, but maybe it is not
routine enough yet to be a good idea to suggest in a learning test.

My goal with learning tests are to prove apis and encourage a "way out" for
certain patterns that isn't subject to collective memory. An anti-goal is
causing confusion or support burden on copy-paste. As I understand the
things you've mentioned, I don't want to put them into a learning/feature
test because it

* suggests we should copy a potentially JVM startup era timestamp to a span
(ex think about normal connection pools!)
* suggests people to use antiquated practice obviated by span.kind (we used
to add "cs' and span.timestamp at the same time)

If you can help clarify why the two above bullets are a misunderstanding of
mine (complete possibility), go for it. Until then, I think the current
tests at least show a pattern which requires the same hooks as you need.
Ex. only by deleting this code, could we remove the api, and that would
force us to look at this issue. Basically we can leave it to how much more
teaching you have patience for :)

**Comment by Logic-32** [comment]
> The span from the past was the connection-scoped one. I might have missed the specific use case you mention, but if you scroll up, you'll notice the connection-scoped span only exists in the past and is only reported if this happens. I don't quite understand why if you are executing a query you'd want to backdate the timestamp.

Right, so again, our use case is probably weird.  But to clarify: we have a span-per-connection.  If multiple queries are executed on that connection we have a way of representing that but it's not with more spans (unfortunately).  Prior to using `abandon()`, we stored the start time for the connection and then on the first execution we called `start(long)`.  This happened because we didn't want to leak any spans if nothing was executed.  Now that we have `abandon()` that is no longer necessary.

> WRT the synchronized timestamp and annotation, honestly I don't understand the use case of this, so don't really want to encourage that practice in a test.. Can you please elaborate why you'd want to do that (ex vs a tag or vs no annotation at all?) remember that "sr" etc should not be added as they are replaced by span.kind

The idea behind that was to show the little annotation bubble in zipkin-ui, meaning we explicitly had to _not_ rely on the `sr` annotation (since it doesn't have a bubble in the UI) but add an extra annotation.  And again, it had to be an annotation because `tags` don't show up in the trace-view of the UI either.  The idea was to use the bubbles for identifying latency between `cs` and `sr` without requiring more complex reporting.

Hopefully these answers to your code-review comments help clarify the above two bullet points.  If not, we can discuss further.  Or I can (probably) write a test to illustrate what I'm talking about more clearly.  Though, the test might not express the rationale very well.

**Comment by adriancole** [comment]
>
> Right, so again, our use case is probably weird. But to clarify: we have a
> span-per-connection. If multiple queries are executed on that connection we
> have a way of representing that but it's not with more spans
> (unfortunately). Prior to using abandon(), we stored the start time for
> the connection and then on the first execution we called start(long).
> This happened because we didn't want to leak any spans if nothing was
> executed. Now that we have abandon() that is no longer necessary.
>
gotit. I missed the span-per-connection (without span per query). Thanks

> WRT the synchronized timestamp and annotation, honestly I don't understand
> the use case of this, so don't really want to encourage that practice in a
> test.. Can you please elaborate why you'd want to do that (ex vs a tag or
> vs no annotation at all?) remember that "sr" etc should not be added as
> they are replaced by span.kind
>
> The idea behind that was to show the little annotation bubble in
> zipkin-ui, meaning we explicitly had to *not* rely on the sr annotation
> (since it doesn't have a bubble in the UI) but add an extra annotation. And
> again, it had to be an annotation because tags don't show up in the
> trace-view of the UI either. The idea was to use the bubbles for
> identifying latency between cs and sr without requiring more complex
> reporting.
>
 You aren't the first to hack the UI by adding more data to your traces.
One problem with this approach is that it puts storage, particularly index
pressure to remedy a case which is likely better solved in javascript. I
opened https://github.com/openzipkin/zipkin/issues/1895 to fix the
javascript. Basically, this seems like a problem in our muting code.

> Hopefully these answers to your code-review comments help clarify the
> above two bullet points. If not, we can discuss further. Or I can
> (probably) write a test to illustrate what I'm talking about more clearly.
> Though, the test might not express the rationale very well.
>
This really does help. Knowing what's up helps identify other problems, and
I think this note particularly did. Thanks!

**Comment by Logic-32** [comment]
You're welcome!  And thanks for the follow up case :)

Out of curiosity, do you have an ETA for when 4.13.4 is going to go out?

**Comment by adriancole** [comment]
>
> Out of curiosity, do you have an ETA for when 4.13.4 is going to go out?
>
sorry missed this! quite a few updates since :)

**Comment by adriancole** [comment]
heh PS I noticed a small problem with clocks still .. yay?!  https://github.com/openzipkin/brave/issues/656 cc @jorgheymans @llinder
