### ISSUE TITLE
Dependent on zipkin?

### ISSUE THREAD

**Issue by jplock** [openzipkin/brave#570]
I'm not sure if this was intentional or not, but due to https://github.com/openzipkin/brave/blob/release-4.13.2/brave/src/main/java/brave/Tracing.java#L135, I had to add:

```java
<dependency>
    <groupId>io.zipkin.java</groupId>
    <artifactId>zipkin</artifactId>
    <version>${zipkin.version}</version>
</dependency>
```

as a dependency in my `dropwizard-zipkin` project because I was getting a compilation error when trying to construct a `Tracing` instance using the builder.

```
[INFO] Compiling 10 source files to /Users/jplock/envs/git/dropwizard-zipkin/zipkin-core/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/jplock/envs/git/dropwizard-zipkin/zipkin-core/src/main/java/com/smoketurner/dropwizard/zipkin/AbstractZipkinFactory.java:[217,17] cannot access zipkin.Endpoint
  class file for zipkin.Endpoint not found
```

**Comment by adriancole** [comment]
zipkin (v1) is now an optional dep, so that people don't need to forever include both io.zipkin.java:zipkin and io.zipkin.zipkin2:zipkin

One way out is to move the internal dependencies to the zipkin2 tree and only use an adapter for whatever cases the zipkin (1) tree is needed (temporary backwards compatibility only I suspect)

Bear in mind the zipkin2 tree can write json in both v1 and v2 format

**Comment by psoares** [comment]
I still have this problem when I try the example with the servlet context listener described at: https://github.com/openzipkin/brave/tree/master/instrumentation/servlet

Here is the dependency I used:
```xml
<dependency>
    <groupId>io.zipkin.brave</groupId>
    <artifactId>brave-instrumentation-servlet</artifactId>
    <version>4.14.1</version>
</dependency>
```

And here is my code:
```java
@WebListener
public class TracingServletContextListener implements ServletContextListener {

  @Override
  public void contextInitialized(ServletContextEvent servletContextEvent) {
    Tracing tracing = Tracing.newBuilder().localServiceName("myservice")
    		.localEndpoint(Endpoint.newBuilder().ip("127.0.0.1").port(9411).build())
    		.build();
    servletContextEvent
        .getServletContext()
        .addFilter("TracingFilter", TracingFilter.create(tracing))
        .addMappingForUrlPatterns(EnumSet.allOf(DispatcherType.class), true, "/*");
  }

  @Override
  public void contextDestroyed(ServletContextEvent servletContextEvent) {
  }
}
```

**Comment by adriancole** [comment]
Should be an optional dep only when compiling code that calls that
deprecated method right?

On 6 Jan 2018 7:04 am, "Justin Plock" <notifications@github.com> wrote:

I'm not sure if this was intentional or not, but due to
https://github.com/openzipkin/brave/blob/release-4.13.2/
brave/src/main/java/brave/Tracing.java#L135, I had to add:

<dependency>
    <groupId>io.zipkin.java</groupId>
    <artifactId>zipkin</artifactId>
    <version>${zipkin.version}</version></dependency>

as a dependency in my dropwizard-zipkin project because I was getting a
compilation error when trying to construct a Tracing instance using the
builder.

[INFO] Compiling 10 source files to
/Users/jplock/envs/git/dropwizard-zipkin/zipkin-core/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/jplock/envs/git/dropwizard-zipkin/zipkin-core/src/main/java/com/smoketurner/dropwizard/zipkin/AbstractZipkinFactory.java:[217,17]
cannot access zipkin.Endpoint
  class file for zipkin.Endpoint not found

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openzipkin/brave/issues/570>, or mute the thread

**Comment by adriancole** [comment]
I think you dont need localEndpoint. Seems like you are listing the zipkin
port which seems invalid as is localhost (localhost doesnt help clarify
this node on the graph)

**Comment by adriancole** [comment]
The reason why this is a problem is that we use overloading with different
types (cc @llinder @marcingrzejszczak @devinsba @shakuzen)

So to compile a call to localEndpoint you need to have old zipkin on the
classpath

In hindsight this was a mistake. We should have not overloaded, rather
choose another name for the method. I see a few options

* do nothing as users dont normally set localEndpoint eventhough frameworks
do sometimes. (Usually default IP is ok). Keep answering this q
* add Tracing.Builder.endpoint(zipkin2.Endpoint) deprecate localEndpoint.
Calls to this wont need zipkin 1 types
* cut brave 5 as same as brave4 but with no zipkin1 dependencies

Thoughts?

**Comment by jplock** [comment]
option 2 or 3 seem fine to me.

**Comment by devinsba** [comment]
I ran into this issue actually, because we are calling `.localEndpoint` I had to have both versions on my libraries path. Wasn't a big deal but would appreciate a fix, if you do anything 2 works for me

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/598

**Comment by adriancole** [comment]
try 4.14.2

**Comment by josiecxx** [comment]
Have the same issue when trying to call [span.remoteEndpoint](https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/Span.java#L129) ...

When I include `io.zipkin.java` so as to have `zipkin.Endpoint`, the sping mvc app fails to startup. wonder if theres any other workaround?

**Comment by Logic-32** [comment]
Probably not relevant any more as v5 is pretty mature, but anyone else stuck on 4.x for a bit will probably encounter this with `Span.remoteEndpoint()` as well.  Ref: https://github.com/openzipkin/brave/blob/4.19.3/brave/src/main/java/brave/Span.java#L119

We're in the process of migrating to v5 but had to make an "emergency" change to address an IntelliJ bug.  That's how I stumbled across this.  Ref: https://youtrack.jetbrains.com/issue/IDEA-198142

**Comment by codefromthecrypt** [comment]
Brave 6.0 will remove the zipkin dependency
