### ISSUE TITLE
Add support for spring-kafka

### ISSUE THREAD

**Issue by Jason0307** [openzipkin/brave#639]
If we have several folks asking for spring-kafka, let's add it. This issue started as Q/A about kafka tracing per below:

> @adriancole  
I see there is kafka instrumentation, but seesm there is no detail docx about how to use it, can some provide an example?

**Comment by adriancole** [comment]
So the readme shows how to decorate a producer and consumer client. Indeed
it doesnt mention how to use them.

What kind of app do you use? Is it spring boot based? What library do you
use to connect to kafka? A bit more detail cam help getting a relevant
example your way.

On 9 Mar 2018 8:40 pm, "Jason" <notifications@github.com> wrote:

@adriancole <https://github.com/adriancole>
I see there is kafka instrumentation, but seesm there is no detail docx
about how to use it, can some provide an example?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openzipkin/brave/issues/639>, or mute the thread

**Comment by Jason0307** [comment]
@adriancole 

Yes, it is spring boot based and we use kafka clients with this version 0.11.0.1.

**Comment by adriancole** [comment]
>
> Yes, it is spring boot based and we use kafka clients with this version
> 0.11.0.1.
>
spring boot with sleuth or on your own? just kafka clients? or do you use a
processing library? or an abstraction like spring-kafka etc?

>

**Comment by Jason0307** [comment]
@adriancole 
On my own and just use kafka clients wihtout spring-kafka.

**Comment by adriancole** [comment]
so the README (I just verified) does have the correct instructions.
https://github.com/openzipkin/brave/tree/master/instrumentation/kafka-clients#processing-messages

Sleuth will shortly have listener spans built in as well https://github.com/spring-cloud/spring-cloud-sleuth/issues/900

**Comment by danielsouza85** [comment]
@adriancole And If i'm using spring-kafka and sleuth to trace? What I have to do to trace producer and consumer?

**Comment by adriancole** [comment]
@danielsouza85 https://github.com/openzipkin/sleuth-webmvc-example/compare/add-kafka-tracing is a working example. I just re-verified it

cc also @jeqo @ImFlog @marcingrzejszczak

**Comment by adriancole** [comment]
re-opening as a feature request

**Comment by adriancole** [comment]
the general dillemma is that some things rely on aop etc or are fast
moving. in brave it is harder to deal with things like this. Specifically
to kafka I think I played with it once, but yeah better to instrument
underneath if we can.

>

**Comment by jeqo** [comment]
Closing as this is solved by https://github.com/openzipkin/sleuth-webmvc-example/commit/ce7e548328b731a08414d34a28a8390a8d978f82
