### ISSUE TITLE
The span name of the request. Defaults should be the http method and path

### ISSUE THREAD

**Issue by JaryZhen** [openzipkin/brave#728]
Personally, I think the [span default name](https://github.com/openzipkin/brave/blob/master/instrumentation/http/src/main/java/brave/http/HttpParser.java) of the request should be method and path.
such as "get - /foo".

    /** Returns the span name of the request. Defaults to the http method. */
     protected <Req> String spanName(HttpAdapter<Req, ?> adapter, Req req) {
        return adapter.method(req)+" - "+adapter.path(req);
     }

**Comment by basvanbeek** [comment]
Given the proliferation of REST services making this default would be a bad idea. You'll end up with very high cardinality in your span names collection.

**Comment by adriancole** [comment]
FYI the name is overwritten when the route can be parsed here: https://github.com/openzipkin/brave/blob/master/instrumentation/http/src/main/java/brave/http/HttpParser.java#L87

Also, you can override this anyway by overriding the parser (which is why we allow it to be overridden).
https://github.com/openzipkin/brave/tree/master/instrumentation/http#span-data-policy

I agree with @basvanbeek that it is too dangerous a default to use path as it will cause problems on the backend and also the user experience on the drop-down for span name.
