### ISSUE TITLE
how to control timestamp between two span

### ISSUE THREAD

**Issue by xiaohongxiedaima** [openzipkin/brave#854]
![tim 20181227120206](https://user-images.githubusercontent.com/8863873/50464998-46aaf500-09cf-11e9-8041-a4315cd7e7de.png)

![tim 20181227114742](https://user-images.githubusercontent.com/8863873/50464723-94bef900-09cd-11e9-8a97-1858e53aba44.png)

i have two application, deploy on different hosts 
app1 have two trace, the `root trace` and `trace1` on `host`
app2 have one trace, the `trace2` on `host2`
and the `trace2` started after `trace1` ,and the `trace2` 's parent_id is `trace1`'s id
because `app1` and `app2` on different hosts,  the timestamp of two hosts are not equles each other
this cause zipkin ui can't show the task dependency in correct
i want to know `how to control the span timestamp before it start` 
thanks!!!

**Comment by xiaohongxiedaima** [comment]
@adriancole

**Comment by adriancole** [comment]
sorry I was on holiday. I am now in china and the images you linked are blocked. you can try https://gitter.im/openzipkin/zipkin for support which is better as other people might be able to help answer questions.

The main way to control time is either to control the brave.Clock used or better yet fix the hosts so that their clocks are closer to synchronized using NTP or similar. Please chat on gitter for more details.
