### ISSUE TITLE
Don't create spans that contain no data

### ISSUE THREAD

**Issue by marcingrzejszczak** [openzipkin/brave#869]
In Sleuth, when working with Reactor or async stuff sometimes we start spans that apparently contain no information whatsoever. Maybe it would be beneficial to discard such spans and just print them out?

Example:

```
23:21:41 {"traceId":"a7fb40fe12da9bf7","id":"a7fb40fe12da9bf7","localEndpoint":{"serviceName":"tracewebfluxtests","ipv4":"172.17.0.1"},"annotations":[{"timestamp":1551219691163000,"value":"brave.flush"}]},
23:21:41     {"traceId":"88e327ba402b1e20","id":"88e327ba402b1e20","localEndpoint":{"serviceName":"tracewebfluxtests","ipv4":"172.17.0.1"},"annotations":[{"timestamp":1551219691163000,"value":"brave.flush"}]},
23:21:41     {"traceId":"853e7fd4c78052de","id":"853e7fd4c78052de","localEndpoint":{"serviceName":"tracewebfluxtests","ipv4":"172.17.0.1"},"annotations":[{"timestamp":1551219691163000,"value":"brave.flush"}]},
```

**Comment by devinsba** [comment]
Hmm, these don't even have a parent. Perhaps a `FinishedSpanHandler` would be a good work around that Sleuth could include in it's chain

**Comment by adriancole** [comment]
trouble is that I dont think the flusher calls finished span handler.
rationale was to not betray the "finished" part of the name. this
annotation is added when data hangs around until gc. in the examples here..
there is no data.

we could build a tool which can help hunt call sites that result in abandon
data but I also agree that sending only span ids might not help in that
hunt... (data here are empty except stock properties)

**Comment by adriancole** [comment]
delayed but not forgotten

**Comment by adriancole** [comment]
@marcingrzejszczak I wonder if this can help identify the root cause? https://github.com/openzipkin/brave/pull/873

**Comment by kurtharriger** [comment]
Our observability team monitors invalid spans and we have been seeing a number of spans being rejected due to no name or timestamp.  

The number of which is relatively low in comparison to overall spans making it difficult to reproduce and find, but all of them are annotated with brave.flush.  The first time I saw this I thought perhaps it was application specific, but I recently bumped a library which transitively bumped brave from  4.19.3 to version: 5.6.3 and started getting invalid spans making me think perhaps this is regression in brave? 

```
{"traceId":"141f2935c0625699","id":"f7a6249df61a386b","localEndpoint":{"serviceName":"cc-page-tree"},"annotations":[{"timestamp":1561670100079000,"value":"brave.flush"}],"tags":{"deployment_id":"qufijqhsr43gfifs","environment":"prod-east","environment_type":"prod","region":"us-east-1","service_version":"2019-06-27_15-58_8ecb850ff7","span_id":"f7a6249df61a386b","trace_id":"141f2935c0625699","worker_group":"WebServer"}} ```

**Comment by adriancole** [comment]
I think this is possibly a different issue and maybe better for gitter but
will answer. please follow up on gitter openzipkin/zipkin or
zipkin-user@googlegroups.com

Can you use brave-bom or otherwise to force latest brave 5.6.5?

if talking about potential regressions easiest to use latest versions that
way we don't re-solve anything. also make sure your app is pointed to v2
endpoint if sending json as sometimes this is the issue.

Also note that the latest zipkin server has better debug messages for
problems. definitely use latest server and enable debug on the category
'zipkin2' to diagnose server side.

**Comment by kurtharriger** [comment]
The changes in library itself were mostly unrelated, BUT it also bumped spring versions and so several related dependencies changed.  Given the annotation is brave.flush it kinda seemed like a brave issue, but could also be something in spring perhaps.  It seems to occur in spikes rather than continuously like maybe when a buffer is full, although some services with higher load seem to encounter the issue less frequently than those with less load so not sure what the trigger is.

I decided to create a hello world service of sorts to see if I can recreate the issue in without mucking with production services where I can have a bit more freedom to experiment and crank up the logging as indicated above.  I'll let you know if I find anything.

**Comment by adriancole** [comment]
yeah brave.flush is usually evidence of an instrumentation bug but the data
mentioned seems ok.

in general esp if elasticsearch load spike issues can happen. there is an
experimental throttle in the latest zipkin release which one site mentioned
reduced their drops.

https://github.com/openzipkin/zipkin/releases/tag/2.14.2

**Comment by kurtharriger** [comment]
The span itself was missing name and timestamp properties.  

I did not have any success recreating the issue in a minimal spring boot application, however I did discover that we were importing  io.zipkin.reporter2:zipkin-sender-urlconnection:2.7.10 instead of version 2.8.4.  I also bumped to latest spring cloud  Greenwich.SR2 version.  One of these things seems to have resolved the issue.
