### ISSUE TITLE
support for filter() in KafkaStreamsTracing

### ISSUE THREAD

**Issue by jorgheymans** [openzipkin/brave#899]
Similar to #889 , it would be nice if the filter operation would be made observable.

Since a filter operation is not a `Processor` but a `Predicate`, it might require a bit more work as current tracing code uses the `ProcessorContext` to access the current trace headers. Any ideas ? I'ld be happy to pilot a PR given some coaching :-) @jeqo

**Comment by jeqo** [comment]
@jorgheymans thanks for taking this one!

We can access headers only by using `Processor` or `Transformer` interfaces, not by "wrapping" existing DSL operations (e.g. KStream#filter). The approach we have choose is to re-implement most common operations as map/peek/foreach.
We can do the same for filter, if you check the internals, filter is implemented by: https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamFilter.java

You could use https://github.com/openzipkin/brave/blob/master/instrumentation/kafka-streams/src/main/java/brave/kafka/streams/KafkaStreamsTracing.java#L221 as guidance to add a filter transfomer. In this case we will receive the Predicate instead of the Mapper as input. Looking forward to your PR!

**Comment by jorgheymans** [comment]
Thanks for the pointers, that's helpful. I'll have a go at implementing this.

Do you think it's useful to tag the span with the result of the filtering (ie filtered=true/false) ?

**Comment by jeqo** [comment]
I think so! you could add a tag: `kafka.streams.filtered`. Without it will be hard to understand why is the last span.
