### ISSUE TITLE
Sampling a Grpc request by matching the method name

### ISSUE THREAD

**Issue by narayaruna** [openzipkin/brave#993]
Provide hooks to be able to plugin a sampler and see the Grpc method name, params and the headers. 

This will be helpful for both b3 and secondary sampling to pick which requests should be traced.

For example consider the following service topology that uses grpc for all of them.

```
playback -> auth
         -> license
```
In the above example, consider a scenario to sample 100% of requests to the method `play(movieId=123)` and the given arguments.

This can achieved today by implementing a grpc ServerInterceptor and running it before the `brave.grpc.TracingServerInterceptor` to check the conditions and inserting the b3 or secondary sampling header.

**Comment by adriancole** [comment]
This implies making a centralized type to represent the grpc request as the parameters are in different places.

Because the types are very much library-specific (ex headers are "Metadata" not plain types), we'd need something here as opposed to an abstraction (over this and other grpc implementations like armeria and wire).

@jorgheymans do you feel up to trying to make a GrpcServerRequest type, then using it as the parameter to extractor.extract?

**Comment by jorgheymans** [comment]
sure will give it a try !

**Comment by adriancole** [comment]
@jorgheymans lemme know if you've work in progress. Otherwise, I can give it a spike as hoping for an integrated demo in the next couple days before I disappear for springoneplatform

**Comment by adriancole** [comment]
#1000 fixes this
